'use client';

import React, { useState, useEffect } from 'react';
import { OnboardingLinksPanel } from '@/components/settings/OnboardingLinksPanel';
import { PendingApprovalsQueue } from '@/components/settings/PendingApprovalsQueue';
import { 
  AUTOMATION_METRICS as INITIAL_METRICS, 
  MAGIC_LINKS as INITIAL_LINKS, 
  PENDING_APPROVALS as INITIAL_APPROVALS,
  MagicLink, 
  PendingApproval 
} from '@/lib/data/mock-settings';
import { Wand2, Clock, CheckCircle2, UserPlus, ShieldAlert } from 'lucide-react';
import { cn } from '@/lib/utils';

interface Toast {
  id: string;
  type: 'success' | 'error' | 'info';
  message: string;
}

export default function AutomatizacionPage() {
  const [magicLinks, setMagicLinks] = useState<MagicLink[]>(INITIAL_LINKS);
  const [pendingApprovals, setPendingApprovals] = useState<PendingApproval[]>(INITIAL_APPROVALS);
  const [metrics, setMetrics] = useState(INITIAL_METRICS);
  const [toasts, setToasts] = useState<Toast[]>([]);

  // Load persistent database on mount
  useEffect(() => {
    const stored = localStorage.getItem('aulacore-pending-approvals');
    if (stored) {
      try {
        setPendingApprovals(JSON.parse(stored));
      } catch (e) {
        console.error(e);
      }
    } else {
      localStorage.setItem('aulacore-pending-approvals', JSON.stringify(INITIAL_APPROVALS));
    }
  }, []);

  const showToast = (message: string, type: 'success' | 'error' | 'info' = 'success') => {
    const id = Math.random().toString();
    setToasts(prev => [...prev, { id, type, message }]);
    setTimeout(() => {
      setToasts(prev => prev.filter(t => t.id !== id));
    }, 4000);
  };

  const handleAddLink = (newLink: MagicLink) => {
    setMagicLinks(prev => [newLink, ...prev]);
    showToast(`Enlace "${newLink.name}" generado y copiado al portapapeles`, 'success');
  };

  const handleApprove = (id: string, notes?: string) => {
    const person = pendingApprovals.find(p => p.id === id);
    if (!person) return;

    const updated = pendingApprovals.filter(p => p.id !== id);
    setPendingApprovals(updated);
    localStorage.setItem('aulacore-pending-approvals', JSON.stringify(updated));

    setMetrics(prev => ({
      ...prev,
      profilesAutoGenerated: prev.profilesAutoGenerated + 1,
      hoursSavedEstimated: prev.hoursSavedEstimated + 2, // 2 administrative hours saved per profile!
      pendingInterventions: Math.max(0, prev.pendingInterventions - 1)
    }));

    showToast(`Perfil de ${person.name} aprobado. Cuenta AulaCore activada con éxito.`, 'success');
  };

  const handleReject = (id: string, notes?: string) => {
    const person = pendingApprovals.find(p => p.id === id);
    if (!person) return;

    const updated = pendingApprovals.filter(p => p.id !== id);
    setPendingApprovals(updated);
    localStorage.setItem('aulacore-pending-approvals', JSON.stringify(updated));

    setMetrics(prev => ({
      ...prev,
      pendingInterventions: Math.max(0, prev.pendingInterventions - 1)
    }));

    showToast(`Solicitud de ${person.name} rechazada.`, 'error');
  };

  const handleCorrectionNeeded = (id: string, notes?: string) => {
    const person = pendingApprovals.find(p => p.id === id);
    if (!person) return;

    const updated = pendingApprovals.map(p => {
      if (p.id === id) {
        return {
          ...p,
          documentStatus: 'Faltante' as const
        };
      }
      return p;
    });
    setPendingApprovals(updated);
    localStorage.setItem('aulacore-pending-approvals', JSON.stringify(updated));

    showToast(`Se ha solicitado corrección a ${person.name}.`, 'info');
  };

  const handleUpdateDocumentStatus = (approvalId: string, docId: string, newStatus: 'Validado' | 'Pendiente' | 'Rechazado') => {
    const updated = pendingApprovals.map(p => {
      if (p.id === approvalId) {
        const updatedDocs = p.documents.map(d => d.id === docId ? { ...d, status: newStatus } : d);
        // Calculate new overall documentStatus based on individual doc statuses
        let overallStatus: 'Validado' | 'Faltante' | 'Revisión Manual' = 'Validado';
        if (updatedDocs.some(d => d.status === 'Rechazado' || d.status === 'Pendiente')) {
          overallStatus = 'Revisión Manual';
        }
        if (updatedDocs.some(d => d.status === 'Pendiente' && d.size === '0 MB')) {
          overallStatus = 'Faltante';
        }
        return {
          ...p,
          documents: updatedDocs,
          documentStatus: overallStatus
        };
      }
      return p;
    });
    setPendingApprovals(updated);
    localStorage.setItem('aulacore-pending-approvals', JSON.stringify(updated));
    showToast(`Estado del documento actualizado.`, 'success');
  };

  const handleSaveObservations = (id: string, observations: string) => {
    showToast(`Observación guardada para el registro.`, 'success');
  };

  return (
    <div className="py-6 space-y-6 max-w-6xl mx-auto animate-in fade-in relative">
      
      {/* Header */}
      <div>
        <h1 className="text-3xl font-black text-slate-900 tracking-tight">Automatización & Links</h1>
        <p className="text-sm text-slate-500 font-medium mt-1">
          Centro de generación de enlaces mágicos y auto-onboarding institucional.
        </p>
      </div>

      {/* KPIs */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm">
          <div className="flex items-center gap-2 text-indigo-600 mb-2">
            <UserPlus className="w-4 h-4" />
            <h3 className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Perfiles Autogenerados</h3>
          </div>
          <p className="text-3xl font-black text-slate-800 transition-all duration-300">{metrics.profilesAutoGenerated}</p>
        </div>
        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm">
          <div className="flex items-center gap-2 text-emerald-600 mb-2">
            <Clock className="w-4 h-4" />
            <h3 className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Horas Ahorradas</h3>
          </div>
          <p className="text-3xl font-black text-slate-800 transition-all duration-300">{metrics.hoursSavedEstimated}h</p>
        </div>
        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm">
          <div className="flex items-center gap-2 text-blue-600 mb-2">
            <CheckCircle2 className="w-4 h-4" />
            <h3 className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Tasa de Completitud</h3>
          </div>
          <p className="text-3xl font-black text-slate-800">{metrics.completionRate}%</p>
        </div>
        <div className="bg-gradient-to-br from-amber-500 to-amber-600 rounded-xl p-5 shadow-sm text-white flex flex-col justify-center transition-all duration-300">
          <h3 className="text-[10px] font-bold uppercase tracking-widest text-amber-100 mb-1">Requieren Aprobación</h3>
          <p className="text-4xl font-black leading-none">{pendingApprovals.length}</p>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 h-[600px]">
        <div className="h-full">
          <OnboardingLinksPanel 
            magicLinks={magicLinks} 
            onAddLink={handleAddLink} 
          />
        </div>
        <div className="h-full">
          <PendingApprovalsQueue 
            pendingApprovals={pendingApprovals} 
            onApprove={handleApprove}
            onReject={handleReject}
            onCorrectionNeeded={handleCorrectionNeeded}
            onUpdateDocumentStatus={handleUpdateDocumentStatus}
            onSaveObservations={handleSaveObservations}
          />
        </div>
      </div>

      {/* Toasts container */}
      <div className="fixed bottom-6 right-6 z-50 space-y-2 pointer-events-none">
        {toasts.map(toast => (
          <div 
            key={toast.id} 
            className={cn(
              "px-4 py-3 rounded-xl shadow-lg border text-xs font-bold pointer-events-auto flex items-center gap-2 animate-in slide-in-from-bottom-2 duration-300 bg-white",
              toast.type === 'success' ? "border-emerald-200 text-emerald-800 bg-emerald-50/90 backdrop-blur-sm" :
              toast.type === 'error' ? "border-rose-200 text-rose-800 bg-rose-50/90 backdrop-blur-sm" :
              "border-slate-200 text-slate-800 bg-slate-50/90 backdrop-blur-sm"
            )}
          >
            {toast.type === 'success' && <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />}
            {toast.type === 'error' && <ShieldAlert className="w-4 h-4 text-rose-600 shrink-0" />}
            {toast.message}
          </div>
        ))}
      </div>

    </div>
  );
}
