export interface AttachedDocument {
  id: string;
  name: string;
  type: string;
  status: 'Validado' | 'Pendiente' | 'Rechazado';
  size: string;
  url?: string;
}

export interface PendingApproval {
  id: string;
  name: string;
  email: string;
  type: 'Docente' | 'Estudiante' | 'Acudiente';
  submittedAt: string;
  status: 'pending_approval';
  documentStatus: 'Validado' | 'Faltante' | 'Revisión Manual';
  autoAssignedCourse?: string;
  documents: AttachedDocument[];
  riskScore?: number; // AI calculated risk for profile anomalies
  observations?: string;
}

export interface MagicLink {
  id: string;
  name: string;
  type: 'Matrícula Abierta' | 'Invitación Docente' | 'Actualización Datos';
  uses: number;
  maxUses: number | 'Ilimitado';
  completed: number;
  abandoned: number;
  status: 'Activo' | 'Expirado';
  createdAt: string;
  lastActive: string;
  url: string;
  autoRole?: string;
}

export const PENDING_APPROVALS: PendingApproval[] = [
  { 
    id: 'app1', name: 'Carlos Mendoza', email: 'cmendoza@edu.co', type: 'Docente', submittedAt: 'Hace 2 horas', status: 'pending_approval', documentStatus: 'Validado', riskScore: 5,
    documents: [
      { id: 'd1', name: 'CV_CarlosMendoza.pdf', type: 'PDF', status: 'Validado', size: '2.4 MB' },
      { id: 'd2', name: 'Titulo_Profesional.pdf', type: 'PDF', status: 'Validado', size: '1.1 MB' }
    ]
  },
  { 
    id: 'app2', name: 'Laura Valentina Pérez', email: 'acudiente.perez@gmail.com', type: 'Estudiante', submittedAt: 'Hace 5 horas', status: 'pending_approval', documentStatus: 'Faltante', autoAssignedCourse: 'Transición A', riskScore: 45,
    documents: [
      { id: 'd3', name: 'Registro_Civil.pdf', type: 'PDF', status: 'Validado', size: '1.8 MB' },
      { id: 'd4', name: 'Carnet_Vacunas.jpg', type: 'IMG', status: 'Pendiente', size: '3.2 MB' },
      { id: 'd5', name: 'Paz_y_Salvo.pdf', type: 'PDF', status: 'Pendiente', size: '0 MB' }
    ]
  },
  { 
    id: 'app3', name: 'Andrés Felipe Gómez', email: 'agomez@edu.co', type: 'Docente', submittedAt: 'Ayer', status: 'pending_approval', documentStatus: 'Revisión Manual', riskScore: 82,
    documents: [
      { id: 'd6', name: 'CV_Actualizado.pdf', type: 'PDF', status: 'Rechazado', size: '4.5 MB' }
    ]
  },
  { 
    id: 'app4', name: 'Familia Ruiz Díaz', email: 'fruiz@hotmail.com', type: 'Acudiente', submittedAt: 'Ayer', status: 'pending_approval', documentStatus: 'Validado', riskScore: 12,
    documents: [
      { id: 'd7', name: 'Documento_Identidad.pdf', type: 'PDF', status: 'Validado', size: '1.2 MB' }
    ]
  },
];

export const MAGIC_LINKS: MagicLink[] = [
  { id: 'ml1', name: 'Matrícula Bachillerato 2026', type: 'Matrícula Abierta', uses: 145, completed: 130, abandoned: 15, maxUses: 'Ilimitado', status: 'Activo', createdAt: 'Hace 2 meses', lastActive: 'Hace 5 min', url: 'aulacore.com/join/bac-2026', autoRole: 'Estudiante' },
  { id: 'ml2', name: 'Onboarding Nuevos Docentes', type: 'Invitación Docente', uses: 4, completed: 4, abandoned: 0, maxUses: 10, status: 'Activo', createdAt: 'Hace 1 semana', lastActive: 'Ayer', url: 'aulacore.com/join/t-xyz89', autoRole: 'Docente' },
  { id: 'ml3', name: 'Actualización Médica Primaria', type: 'Actualización Datos', uses: 89, completed: 50, abandoned: 39, maxUses: 300, status: 'Activo', createdAt: 'Hace 3 días', lastActive: 'Hace 1 hora', url: 'aulacore.com/update/med-pri', autoRole: 'Acudiente' },
];

export const AUTOMATION_METRICS = {
  profilesAutoGenerated: 412,
  hoursSavedEstimated: 124,
  completionRate: 94,
  pendingInterventions: 4
};
